## tpoic last session
- arange,linspace
- random
   - randint
   - randn
   - normal
- basic operations +,-,*,/,//
- initializing arrays
   - zeros
   


In [5]:
import numpy as np
a=np.arange(7)
b=np.full((7),1)

In [6]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[1 2 3 4 5 6 7]
[-1  0  1  2  3  4  5]
[0. 1. 2. 3. 4. 5. 6.]


In [8]:
#create a 3d array
np.random.seed(23)
a3=np.random.randint(100,size=(3,5,4))
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [9]:
for i in a3:
    print(i)
    break

[[83 40 73 54]
 [31 76 91 39]
 [90 25 51  6]
 [45 12 49 66]
 [75 85 69 64]]


In [10]:
#slicing or subsetting
a3[:]#it will give all the elements with same dimension

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [18]:
a3[1]#2nd 5*3 array  shape(5,4)
#np.shape(a3[1])


array([[12, 21, 48, 41],
       [79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1],
       [43, 15, 86, 83]])

In [12]:
a3[:1]# a3[0]a 5*3 array shape(5,4)


array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [13]:
a3[:2] #shape(2,5,4)

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]]])

In [15]:
np.shape(a3[:2])

(2, 5, 4)

In [20]:
a3[0][2][2]

51

In [21]:
a3[1,:,2]

array([48, 62, 59, 65, 86])

In [22]:
a3


array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [23]:
a3[:2,1:3,2]# :2 means dimensions
            # 1:3 in the two dimensins we get the second and third row
            #2 means we access the third column
            # every matrix starts from 0 row and 0 column

array([[91, 51],
       [62, 59]])

In [24]:
a3[[2,1,0]]

array([[[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [25]:
a3[:,[3,1]]# all the dimensions access the 4th row and 1st row

array([[[45, 12, 49, 66],
        [31, 76, 91, 39]],

       [[15, 36, 65,  1],
        [79, 90, 62, 57]],

       [[94, 78,  0, 21],
        [35, 96, 56, 13]]])

In [33]:
a3[[2,1],[1,3],[3,2]] #[2,1,3][1,3,2] broadcasting

array([13, 65])

In [29]:
a3[2,1,3],a3[1,3,2]

(13, 65)

In [38]:
#np.random.seed(0)
a2=np.random.randint(100,size=(5,7))
a2

array([[49, 29, 19, 19, 14, 39, 32],
       [65,  9, 57, 32, 31, 74, 23],
       [35, 75, 55, 28, 34,  0,  0],
       [36, 53,  5, 38, 17, 79,  4],
       [42, 58, 31,  1, 65, 41, 57]])

In [46]:
#select alternate columns
#select alternate rows
#a2[:,[0,2,4]]
#a2[:,[1,3,5]]
#a2[:,0::2]
a2[:,1::2]


array([[29, 19, 39],
       [ 9, 32, 74],
       [75, 28,  0],
       [53, 38, 79],
       [58,  1, 41]])

In [47]:
a2[0:2,]

array([[49, 29, 19, 19, 14, 39, 32],
       [65,  9, 57, 32, 31, 74, 23]])

In [48]:
a2[[0,2,4],:]

array([[49, 29, 19, 19, 14, 39, 32],
       [35, 75, 55, 28, 34,  0,  0],
       [42, 58, 31,  1, 65, 41, 57]])

In [49]:
a2[1::2,:]

array([[65,  9, 57, 32, 31, 74, 23],
       [36, 53,  5, 38, 17, 79,  4]])

In [50]:
a2[[1,3],:]

array([[65,  9, 57, 32, 31, 74, 23],
       [36, 53,  5, 38, 17, 79,  4]])

In [52]:
a2=np.arange(35).reshape(5,7)
a2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [53]:
#check the output
a2[[1,2,0],[2,4,6]]#[(1,2),(2,4,(0,6))] broadcast avuthundi

array([ 9, 18,  6])

In [62]:
a2[2:3:5]

array([[14, 15, 16, 17, 18, 19, 20]])

In [59]:
a2>10

array([[False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [65]:
print(True+True)
print(True+False)

2
1


In [64]:
np.sum(a2>10)

24

In [66]:
a2[a2>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34])

In [67]:
a5=np.array([67,89,23,44,32,78,99])
a5 %2==0

array([False, False, False,  True,  True,  True, False])

In [68]:
a5[a5 %2==0]#even

array([44, 32, 78])

In [70]:
a5[a5 %2==0] = 0
a5

array([67, 89, 23,  0,  0,  0, 99])

In [71]:
a5=np.array([67,89,23,44,32,78,99])
a5 %2!=0

array([ True,  True,  True, False, False, False,  True])

In [72]:
a5[a5 %2!=0]#odd

array([67, 89, 23, 99])

In [79]:
a6=np.array([92,-127,89,-34,2,67])
#np.abs(a6)
a6[a6<0]=[127,34]
a6

array([ 92, 127,  89,  34,   2,  67])

In [80]:
a6=np.array([92,-127,89,-34,2,67])
np.abs(a6)

array([ 92, 127,  89,  34,   2,  67])

In [81]:
np.mean(a6)

14.833333333333334

In [82]:
a6=np.array([92,-127,89,-34,2,67])
#np.abs(a6)
a6[a6<0]=np.mean(a6)
a6

array([92, 14, 89, 14,  2, 67])

## array manipulation
  - reshape
  - flatten
  - resize
  

In [85]:
a7=np.arange(45).reshape((9,5))
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [86]:
a7.reshape(1,9,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [87]:
a7.reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [90]:
a7.reshape(5,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [91]:
a7.reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [92]:
a7.reshape(3,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [96]:
a7.reshape(5,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [ ]:
a7.reshape(5,4,-1) #error

In [97]:
a7


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [102]:
a7.resize(5,9)
a7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [103]:
np.resize(1,5)

array([1, 1, 1, 1, 1])

In [104]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [105]:
help(a7.resize)

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This realloca

In [106]:
np.resize(a7,(5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44,  0,  1,  2,  3,  4]])

In [107]:
a7.shape

(5, 9)

In [108]:
a7.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [109]:
a7


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [113]:
a7.reshape(1,5*9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [119]:
a7.reshape(5*9)
a7.reshape(-1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [125]:
help(np.swapaxes)

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [127]:
np.swapaxes(a7,0,1)

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

In [128]:
a7.shape

(5, 9)

In [131]:
np.swapaxes(a7,0,1).shape

(9, 5)

In [132]:
a7


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [133]:
import math
math.log(2)

0.6931471805599453

In [135]:
np.log([1,2,3,4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [136]:
np.log1p(1)#np.log1p(x)=np.log(1+x)

0.6931471805599453

In [137]:
np.log1p(0)

0.0

exponential

In [138]:
np.exp(1)

2.718281828459045

In [ ]:
#esc+h short cuts

In [152]:
np.exp2(2)

4.0

In [153]:
np.expm1(2)#np.exp()-1

6.38905609893065

In [158]:
np.exp(2)-1

6.38905609893065