In [10]:
import numpy
numpy.__version__

'1.16.5'

In [11]:
import numpy as np
np.__version__

'1.16.5'

In [12]:
a=[1,2,3]
b=[1,2,3]
map(lambda a,b:a+b)

TypeError: map() must have at least two arguments.

In [13]:
import numpy as np
import numpy
a1=np.array(a)
print(type(a1))
print(a1)
print(a1.dtype)
print(a)

<class 'numpy.ndarray'>
[1 2 3]
int32
[1, 2, 3]


In [14]:
a1**2


array([1, 4, 9], dtype=int32)

In [15]:
n=list(range(100000))
import time
start=time.time()
n1=[i**2 for i in n]
end=time.time()
print(end-start)

0.03125309944152832


In [17]:
n=np.arange((100000))
import time
start=time.time()
n1=n**2
end=time.time()
print(end-start)

0.015625715255737305


In [18]:
t1=np.array((1,2,3))
print(type(t1))
print(t1.dtype)

<class 'numpy.ndarray'>
int32


In [21]:
t1=np.array((1,2,3),dtype=np.int8)
print(type(t1))
print(t1.dtype)
print(t1.size) # to check the no of elements
print(t1.shape[0])

<class 'numpy.ndarray'>
int8
3
3


In [22]:
np.arange(3.5,9,0.5)

array([3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5])

In [3]:
#import the package
import numpy as np

In [4]:
#create a numpy 2d array
l=[[23,45],[67,89],[56,78]]
a2=np.array(l)

In [10]:
#ndim-no of dimensions
print(a2.ndim)
#shape-shape as a tuple
print(a2.shape)
#size-no of elements
print(a2.size)
#itemsize-return no of bytes required to store an element 
print(a2.itemsize)
#dtype-data type of the numpy array
print(a2.dtype)
#total size of the array
print(a2.size*a2.itemsize)


2
(3, 2)
6
4
int32
24


In [15]:
for i in a2:
    print(type(i))
    break
    


<class 'numpy.ndarray'>


In [16]:
for i in l:
    print(i)
    print(type(i))

[23, 45]
<class 'list'>
[67, 89]
<class 'list'>
[56, 78]
<class 'list'>



## initializing array
  - np.zeros
  - np.ones
  - np.eye
  - np.full
  - np.arange

In [20]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [22]:
np.ones((3,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [26]:
[[False,False]],[False,False]

([[False, False]], [False, False])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [31]:
np.full((3,2),9.7)

array([[9.7, 9.7],
       [9.7, 9.7],
       [9.7, 9.7]])

In [32]:
np.diag([7,9,23])

array([[ 7,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 23]])

In [33]:
np.diag([1,1,])

array([[1, 0],
       [0, 1]])

In [34]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [35]:
np.eye(3,k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
array[[.,1.,]]

In [20]:
#import numpy as np
print(np.arange(10))
print(np.arange(2,10))
print(np.arange(2,10,2))
print(np.arange(2,5,0.5))



[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[2.  2.5 3.  3.5 4.  4.5]


In [21]:

print(np.linspace(5,10,2))
print(np.linspace(5,10,3))
print(np.linspace(5,10,4))


[ 5. 10.]
[ 5.   7.5 10. ]
[ 5.          6.66666667  8.33333333 10.        ]


In [6]:
a=np.array([1,2,3])
b=np.array([1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)


[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[1 2 3]
[0 0 0]
[1 2 3]


In [7]:
a+1

array([2, 3, 4])

In [8]:
a+[1]

array([2, 3, 4])

In [9]:
a+[1,1]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [14]:
b1=np.full((3,4,2),2)
b2=1
b3=np.array([2,3])
b4=np.array([[1],[2]])

In [16]:
print(b3.shape,b4.shape)
b3+b4

(2,) (2, 1)


array([[3, 4],
       [4, 5]])

In [17]:
b3


array([2, 3])

In [18]:
b4

array([[1],
       [2]])

In [24]:
b1=np.full((3,4,2),2)
b5=np.full((1,3,1,2),4)


In [25]:
b1+b5

array([[[[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]]]])

In [26]:
(b1+b5).shape

(1, 3, 4, 2)

In [29]:
a=np.arange(25)
print(a[:2])
print(a[5:10])
print(a[2:24:5])
print(a[1])
print(a[-1])
print(a[[2,5,9]])#pass the list indices
print(a[[24,2,1,6]])

[0 1]
[5 6 7 8 9]
[ 2  7 12 17 22]
1
24
[2 5 9]
[24  2  1  6]


random

In [30]:
np.random.randint(7,10,(2,2))#the third parameter is shape of output array 

array([[8, 9],
       [7, 7]])

In [31]:
np.random.randint(1,10,(2,2))

array([[7, 6],
       [9, 8]])

In [33]:
np.random.random()

0.03286839754211357

In [34]:
np.random.random((4,5))

array([[0.70374642, 0.16248306, 0.51099538, 0.36909916, 0.06701644],
       [0.84374232, 0.95123884, 0.92679331, 0.9745721 , 0.15633884],
       [0.19788886, 0.19993169, 0.97091187, 0.66377509, 0.44120399],
       [0.10970892, 0.79944417, 0.12929282, 0.64530725, 0.08125714]])

In [38]:
np.random.normal()#normal distribution curve

-0.5471341940641499

In [37]:
np.random.randn()

1.067087009906693

In [39]:
np.random.randn(2,3)

array([[-0.2142382 , -0.08145156, -0.61259306],
       [-2.55197556, -0.30562684,  0.81876753]])

In [40]:
np.random.normal((2,3))

array([1.06894782, 3.99113359])

In [41]:
help(np.random.normal())

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

In [44]:
dir (np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [49]:
a1=np.array([10,20,30,40,50])
np.min(a1)

10

In [50]:
np.max(a1)

50

In [51]:
np.mean(a1)

30.0

In [54]:
np.quantile(a,0.25)

6.0

In [55]:
np.quantile(a,0.5)

12.0

In [56]:
np.quantile(a,0.75)

18.0

In [60]:
a=np.array([[2,3],[4,5]])
np.sum(a)

14

In [61]:
a=np.array([[2,3],[4,5]])
np.sum(a,axis=0)

array([6, 8])

In [70]:
a=np.array([[2,3],[4,5]])
np.sum(a,axis=1,keepdims=True)

array([[5],
       [9]])

In [68]:
a

array([[2, 3],
       [4, 5]])

In [71]:
def param():
    '''hi how are you '''

In [72]:
help(param)

Help on function param in module __main__:

param()
    hi how are you



In [1]:
import param 
print(param.x)



10


In [2]:
if -40:
    print("your name")

your name


In [3]:
if "":
    print("mjm")

In [4]:
bool("")

False

In [5]:
bool(" ")

True

In [6]:
l=[1,2,3]
[i**0.5 for i in l]

[1.0, 1.4142135623730951, 1.7320508075688772]