In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.16.5


In [11]:
a=np.zeros(10)
print(a)
type(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.ndarray

In [13]:
np.size(a)

10

In [17]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [19]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [21]:
a=np.arange(10)
a[4]=1
print(a)

[0 1 2 3 1 5 6 7 8 9]


In [28]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
a=np.array([1,2,0,0,4,0])
b=np.where(a!=0)
print(b)


(array([0, 1, 4], dtype=int64),)


In [46]:
#another method
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [53]:
z=np.eye(3)#creation of identity matrix
print (z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
a=np.random.random((3,3,3))
type(a)
a

array([[[0.91131264, 0.63793952, 0.7592144 ],
        [0.12319986, 0.2583174 , 0.95123798],
        [0.05653863, 0.20381126, 0.66422689]],

       [[0.71415467, 0.04374431, 0.88043278],
        [0.37674084, 0.64062636, 0.04912839],
        [0.00337034, 0.95048016, 0.04922786]],

       [[0.14205558, 0.20798116, 0.18923274],
        [0.74478519, 0.85616311, 0.41124216],
        [0.64498762, 0.09917684, 0.47314835]]])

In [72]:
a=np.random.random((10,10))
min=a.min()
max=a.max()
print(min)
print(max)
np.size(a)

0.005587196488835988
0.9602500037875084


100

In [73]:
a=np.random.random(30)
m=a.mean()
m

0.4896261282133297

In [78]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [79]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [80]:
print(np.nan==np.nan)

False


In [83]:
print(0*np.nan)

nan


In [84]:
print(np.inf>np.nan)

False


In [85]:
print(np.nan-np.nan)

nan


In [86]:
print(np.nan in set([np.nan]))

True


In [87]:
print(0.3==3*0.1)

False


In [88]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [93]:
z=np.zeros((8,8),dtype=int)
z[1:2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]


In [94]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [96]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
z=np.random.random((5,5))
z=(z-np.mean(z))/(np.std(z))
print(z)

[[ 1.48330934  0.03008021  0.55855297  0.17538042 -0.41465757]
 [ 1.92673693 -0.89437084  1.68726589  0.17423349 -1.15380471]
 [-0.36402481 -1.41001496 -1.03415037 -1.01685769  0.28415152]
 [-0.72547106  0.68360313 -0.73497591  0.37024268 -1.41367786]
 [-0.65452514 -0.61239875 -0.03527727  1.61061049  1.48003988]]


In [99]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

In [100]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [104]:
z=np.arange(11)
z[(3<z)&(z<=8)] *=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [117]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


In [118]:
print(sum(range(5)))

10


In [124]:
print(np.array(0)/np.array(0))

nan


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [131]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[-1. -8.  7.  3. -2. -9.  1.  7.  1. -9.]


In [139]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[1 3 4 6]


In [146]:
default=np.seterr(all="ignore")
z=np.ones(1)/0
_=np.seterr(**default)
#An equivalent way,with acontext manager:
with np.errstate(divide='ignore'):
        z=np.ones(1)/0

In [147]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

In [149]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [150]:
print(yesterday)
print(today)
print(tomorrow)


2020-01-08
2020-01-09
2020-01-10
