### numpy 101 excercises
#### website-- https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
import numpy as np
print(np.__version__)

1.16.5


In [10]:
arr=np.array([1,2,3,4,5,6])
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [15]:
np.full((3,3),0,dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.full((3,3),20,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [5]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]


array([1, 3, 5, 7, 9])

In [9]:
arr[arr%2==1]=-1
arr
    


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
out=np.where(arr%2==1,-1,arr)
out
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

In [34]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [60]:
#vertical
a=np.arange(10).reshape(2,-1)
#print(a)
b=np.repeat(1,10).reshape(2,-1)
#print(b)
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
np.r_[a,b]#vertical

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
help(np.concatenate)

Help on built-in function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equ

In [61]:
#horizontal
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [62]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [70]:
a=np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [76]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [81]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [85]:
help(np.setdiff1d)

Help on function setdiff1d in module numpy:

setdiff1d(ar1, ar2, assume_unique=False)
    Find the set difference of two arrays.
    
    Return the unique values in `ar1` that are not in `ar2`.
    
    Parameters
    ----------
    ar1 : array_like
        Input array.
    ar2 : array_like
        Input comparison array.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.
    
    Returns
    -------
    setdiff1d : ndarray
        1D array of values in `ar1` that are not in `ar2`. The result
        is sorted when `assume_unique=False`, but otherwise only sorted
        if the input is sorted.
    
    See Also
    --------
    numpy.lib.arraysetops : Module with a number of other functions for
                            performing set operations on arrays.
    
    Examples
    --------
    >>> a = np.array([1, 2, 3, 2, 4, 1])
    >>> b = np.array([3, 4, 5, 6])
    >>> np.setdiff1d

In [89]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


(array([1, 3, 5, 7], dtype=int64),)

In [95]:
a=np.arange(15)
out=np.where((a>=5)& (a<=10))
(a[out])

array([ 5,  6,  7,  8,  9, 10])

In [5]:
import numpy as np
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(a,b):
    if a>=b:
        return a
    else:
        return b
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [112]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(a,b):
    if a>=b:
        return a
    else:
        return b
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [15]:
#swapping of columns
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]#arr[[index 1,index 0,index 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [17]:
arr=np.arange(9).reshape(3,3)
arr
arr[[1,0,2]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [18]:
#reverse of the rows
arr=np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [21]:
#reverse of the columns
arr
arr[:,::-1]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [38]:
arr=np.arange(9).reshape(3,3)
random=np.random.randint(low=5,high=10,size=(5,3))+np.random.random((5,3))
print(random)

[[9.67935194 8.56392099 6.79109016]
 [6.73559905 8.13480505 7.70051336]
 [9.34388658 6.82794088 7.09990516]
 [5.53311947 9.24006369 9.73050446]
 [7.09022325 9.38577181 7.39754218]]


In [4]:
import numpy as np
random=np.random.random((5,3))
print(random)

[[0.33181555 0.67684802 0.79131979]
 [0.08145688 0.08600184 0.01274431]
 [0.15902459 0.22235348 0.47962736]
 [0.38167023 0.5041738  0.60336164]
 [0.59803674 0.14777519 0.34314707]]


In [11]:
random=np.random.random((5,3))
np.set_printoptions(precision=3)
random

array([[0.716, 0.163, 0.41 ],
       [0.195, 0.403, 0.999],
       [0.251, 0.175, 0.962],
       [0.867, 0.589, 0.366],
       [0.708, 0.097, 0.952]])

In [15]:
import numpy as np
np.set_printoptions(threshold=6)
#np.set_printoptions(threshold=np.nan)22,23,24 doubts
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])