### trignometric function

In [2]:
import numpy as np
a=np.random.randint(100,size=23)
np.sin(a)

array([ 0.67022918, -0.2794155 ,  0.98662759, -0.76825466,  0.74511316,
        0.55142668,  0.31322878,  0.63673801, -0.96611777, -0.99975517,
        0.42016704,  0.43616476,  0.86006941, -0.95375265, -0.94828214,
        0.65028784,  0.83665564, -0.95375265,  0.77389068,  0.67022918,
       -0.98514626, -0.99999021, -0.17607562])

In [3]:
np.sin(3.14/2)

0.9999996829318346

In [4]:
np.arcsin(1)

1.5707963267948966

In [5]:
np.rad2deg(1.5707963267948966)

90.0

In [6]:
np.deg2rad(90)

1.5707963267948966

In [7]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [10]:
math.sin(2)

0.9092974268256817

### log and exponential functions

In [11]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [13]:
print(np.log2(2))
print(np.log2(32))


1.0
5.0


In [15]:
np.log(2+1)

1.0986122886681098

In [16]:
np.log1p(2)
#np.log1p(x)=np.log(1+x)

1.0986122886681098

In [17]:
print(np.exp(1))

2.718281828459045


In [18]:
print(np.exp2(2))

4.0


In [20]:
print(np.expm1(5))
print(np.exp(5)-1)
#np.expm1(x)=np.exp(x)-1

147.4131591025766
147.4131591025766


## statistics

In [22]:
a=np.random.randint(100,size=5)
a

array([15, 72, 48, 12, 31])

In [25]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

178
178
35.6
31.0
22.2764449587451


In [28]:
np.sort(a)

array([12, 15, 31, 48, 72])

In [29]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))


15.0
31.0
48.0


## broadcasting

In [31]:
a=np.arange(3)
b=np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [32]:
a=np.arange(10).reshape(5,2)
b=np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [33]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
a=np.arange(10).reshape(5,2)
b=np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

## broadcasting
- last values having same size or ex(2,3)(3) yes
ex(3,2)(3) no
- last value one of them containing 1's(3,1)(2)yes (3,2)(1)yes

In [36]:
a=np.arange(10).reshape(5,2)
b=np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

In [38]:
a=np.arange(15).reshape(5,3,1)
b=np.arange(5)
a+b

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6]],

       [[ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9]],

       [[ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12]],

       [[ 9, 10, 11, 12, 13],
        [10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

# vectorize

In [41]:
a=np.arange(15).reshape(5,3)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [43]:
np.random.seed(5)
a=np.random.randint(50,size=10)
b=np.random.randint(50,size=10)
print(a)
print(b)


[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [46]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)


44

In [47]:
maxnumber_vec=np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

## stacking

In [49]:
a=np.arange(6)
b=np.arange(6)
np.hstack([a,b])

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [50]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [52]:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)
np.hstack([a,b])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [53]:
a=np.arange(6).reshape(2,3)
b=np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

# linear algebra

In [54]:
np.linalg.det(np.eye(2))

1.0

In [57]:
np.linalg.det(np.array([[1,2],[5,7]]))

-2.999999999999999

In [58]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [59]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [63]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 

In [66]:
print(np.dot(a,b))
print(a)
print(b)

[ 5 14]
[[0 1 2]
 [3 4 5]]
[0 1 2]


In [43]:
import datetime
f=open('data.txt')
data=f.read()
data=eval(data)
data

[{'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 520},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 521},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 523},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 524},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 530},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 531},
 {'attendance': 'A',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 533},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 534},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
 

In [10]:
print(a[1]['date'])
  

NameError: name 'a' is not defined

In [44]:
import datetime
f=open('studentid.txt')
studentid=f.read()
studentid=eval(studentid)
studentid.sort()
print(studentid)


[457, 459, 460, 461, 462, 463, 464, 466, 467, 468, 469, 471, 472, 473, 474, 475, 476, 477, 478, 480, 482, 484, 485, 486, 487, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 505, 506, 507, 508, 509, 510, 511, 512, 513, 515, 516, 517, 518, 520, 521, 523, 524, 530, 531, 533, 534, 535, 536, 539, 540, 541, 544, 546, 549, 550, 551, 552, 555, 556, 557, 558, 560, 561, 563, 564, 565, 568, 569, 572, 574, 575, 576, 578, 579, 580, 774, 775, 776, 777, 778, 781, 783, 784, 785, 786, 787, 788, 789, 791, 792, 793, 795, 796, 797, 798, 800, 803, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 904, 905, 906, 908, 909, 911, 912, 914, 915, 917, 918, 919, 921, 923, 924, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 953, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 1033, 103

In [12]:
a

NameError: name 'a' is not defined

In [13]:
for i in data:
    print(i)
    break

{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 520}


In [22]:
len(studentid),len(data)

(363, 2176)

In [18]:
for i in range(len(data)):
    for j in range(len(studentid)):
        if data[i]['student_id']== studentid[j]:
            fdata= data[i]
            print(fdata)              

{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 520}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 521}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 523}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 524}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 530}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 531}
{'attendance': 'A', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 533}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 534}
{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 21), 'level': 3, 'student_id': 535}
{'attendance': 'P', 'session': 'FN', 'date': datetime.d

{'attendance': 'P', 'session': 'FN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 967}
{'attendance': 'A', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 915}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 904}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 905}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 906}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 908}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 909}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 911}
{'attendance': 'P', 'session': 'AN', 'date': datetime.date(2019, 12, 24), 'level': 3, 'student_id': 912}
{'attendance': 'P', 'session': 'AN', 'date': datetime.d

In [69]:
dates1=[x['date'] for x in data]
print(dates1)

[datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date(2019, 12, 21), datetime.date

In [28]:
setdates=list(set(dates1))
setdates 

[datetime.date(2019, 12, 21),
 datetime.date(2019, 12, 23),
 datetime.date(2019, 12, 24)]

In [25]:
fdata

{'attendance': 'P',
 'session': 'AN',
 'date': datetime.date(2019, 12, 23),
 'level': 3,
 'student_id': 563}

In [57]:
data[0]

{'attendance': 'P',
 'session': 'FN',
 'date': datetime.date(2019, 12, 21),
 'level': 3,
 'student_id': 520}

In [58]:
x = data[0]
if ((x['date']==setdates[0]) and (x['student_id']==520)) and (x['session']=='FN'):
    print('hello')

hello


In [93]:
d={}
for i in studentid:
    for j in range(len(setdates)):
        for session in ['FN','AN']:
            flag=False
            for x in data:
                if ((x['date']==setdates[j]) and (x['student_id']==i)) and (x['session']==session):
                    if i in d:
                        d[i].append(x['attendance'])
                    else:
                        d[i]=[x['attendance']]
                    flag= True
                    break
            if flag==False:
                if i in d:
                        d[i].append('NA')
                else:
                        d[i]=['NA']
                    
        